### ISSUE TITLE
Exam enhancements (from the MST125 team)

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#21] opened 2016-11-30 10:06 UTC
Hi Robert,
During production of an MST125 exam, the team had the following comments; I'll be happy to contribute the development of them, and thought that I'd log them here for reference.
Best
Chris

21.1: Shrink the margin comments and use a different font; the margins in the questions are fine (except that the real, blank margin widths should be different on left/right pages, as noted below), but the width for the comments in the solutions is too narrow.   I’ve had to do some fiddling with comments (e.g. moving them around and creative use of abbreviations) to try to get them not overlapping.

21.2: Lines to separate the solution parts (*should be able to copy/re-use code from outn.cls*)

21.3: Solution subtotals (*should be able to copy/re-use code from outn.cls* -- perhaps a common .sty file between the two would be sensible...?)

21.4: There doesn’t seem to be any way to produce the solutions only, or to produce the solutions appended at the end of the question paper (unless I’ve missed something, which I could have).  Do we want to ask about that?  Or do you think we only ever want each question and solution together?   Personally, for marking, I don’t really want the questions – instead I’d prefer to have the solutions on as few pages as possible.  (*cmhughes: I'm interested in exploring this, and it's something that I'd like to implement in ouab.cls as well*)

21.5: The blank margins in the question paper should adjust for left/right pages.  (E.g. the page numbers should be the same distance from the edge of the page on left/right pages.)

**Comment by rbrignall** [comment] 2016-11-30 10:40
Hi Chris,
Thanks for compiling these. A few comments:
21.1: Seems fine. Perhaps use "\small". That may be sufficiently different to distinguish from the text. (Fonts can introduce issues with miktex/texlive installations...)

21.2: Seems fine to roll over the stuff from `outn`. Note LaTeX already provides `\hline` -- there'd need to be a good reason why this isn't enough for massive extra effort. Authors have been used to OUTeX providing for every eventuality (largely because there was no way for authors to do their own thing), but now we have standard LaTeX, authors can do anything they want. The key thing is not to overcomplicate our class files. 

21.3: Yes, re-use the code from outn. For now, don't create a shared sty file: we need to keep everything for each class in a single class file for ease of use by authors. We can refactor and share common code once/if we get it onto CTAN in future. 

21.4: Authors have several options already. e.g.:
a) Using the `solutions` environment to produce exam and solutions from the same tex source. This will print solutions underneath the question (my preferred way of working, as it happens!).
b) At some near-final stage, duplicate the tex file so that there is one for solutions (possibly with the questions deleted), and one for the exam. This would produce "solutions only".
c) Instead of using the solutions environment, at the end of the file use the `\solutions` command (per subsection 5.4 of the documentation). This produces solutions at the end of the document.
d) There is no requirement for authors to use the ouexam.cls file to produce solutions if they prefer something else. 
That said, there _is_ an improvement that we could make here: creating a `solutionsatend` option that moves the contents of the `solutions` environments to the end of the document, with appropriate numbering. This needs to be done with care, because it will screw up anything written in `verbatim` (so if the solutionsatend option is not switched on, `verbatim` should work as expected). 

21.5: This style is copied over from OUTeX (and took some work to reproduce!), so I'd caution against changing it without agreement from other stakeholders (LTS) who might have reasons for the way it was. Also worth noting that you need wide margins always on the right in solutions, to allow margin comments.

**Comment by rbrignall** [comment] 2017-10-16 16:06
21.1 Font size adjusted in b1273bb. 
Could consider adjusting margins when showsolutions option is on. 
Overlapping marginpars are a "feature" of `marginnote`, but could use, e.g. `\renewcommand*{\marginnotevadjust}{40pt}`

21.2 @cmhughes could you move relevant code over from outn?

21.3 @cmhughes could you move relevant code over from outn?

21.4 Long-term enhancement, moved to #37.

21.5 Blank margins are set by university, cannot be changed.

**Comment by cmhughes** [comment] 2017-10-18 11:20
I'll be happy to copy the relevant code from `outn` for 21.2 and 21.3. I'd hope to be able to tackle this by the end of October 2017, but will report back if that isn't possible.

One side note that I've been thinking of: I'd find it helpful to have a batch of test-cases that we could bench mark against. A possible way to implement this would be to host some `.tex` files that illustrate all of the different switches/options in a directory named (say) `test-cases` for which we produce post-script files in a batch; we could track the post-script files using `git` so that we could measure any changes from new features/bug fixes.

**Comment by rbrignall** [comment] 2017-10-18 12:42
#21.1 "fixed" (by documenting an existing feature that came automatically from the `marginpar` package).

This leaves #21.2 and #21.3 before this issue list can be closed.

**Comment by rbrignall** [comment] 2017-11-16 14:20
@cmhughes I'm going to take a stab at #21.2 and #21.3 this afternoon. Please shout if you've already made a start on these!

**Comment by rbrignall** [comment] 2017-11-16 16:37
#21.2 and #21.3 now implemented. (N.B. warning about this code using \rule instead of \hrule.)

Closing this issue.

**Closed as completed by rbrignall** 2017-11-16 16:37 UTC

**Comment by cmhughes** [comment] 2017-11-16 16:59
I'm so sorry I didn't get to these in time, thanks a lot for taking care of
them.
